// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCqNUYvF9iHC-6KuUxF0-xvJZz-CTvoKo',
    appId: '1:417425143766:android:d642871a6f955b65dbd677',
    messagingSenderId: '417425143766',
    projectId: 'cricbid-20a35',
    storageBucket: 'cricbid-20a35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlIBkVdyXO0PE_49QhHmLmmilIKXGhqJU',
    appId: '1:417425143766:ios:55b28d921a7577fadbd677',
    messagingSenderId: '417425143766',
    projectId: 'cricbid-20a35',
    storageBucket: 'cricbid-20a35.firebasestorage.app',
    iosBundleId: 'com.cricbid.cricbid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlIBkVdyXO0PE_49QhHmLmmilIKXGhqJU',
    appId: '1:417425143766:ios:55b28d921a7577fadbd677',
    messagingSenderId: '417425143766',
    projectId: 'cricbid-20a35',
    storageBucket: 'cricbid-20a35.firebasestorage.app',
    iosBundleId: 'com.cricbid.cricbid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_ysoVwtsWL_w5_e1imTcW4EFUvpXKHOA',
    appId: '1:417425143766:web:d61d630d84f3e1dbdbd677',
    messagingSenderId: '417425143766',
    projectId: 'cricbid-20a35',
    authDomain: 'cricbid-20a35.firebaseapp.com',
    storageBucket: 'cricbid-20a35.firebasestorage.app',
    measurementId: 'G-29RT1DHH48',
  );
}
